services:
  - type: web
    name: newsr-app
    env: node
    plan: free
    rootDir: .
    buildCommand: npm ci && npm run build
    startCommand: npm start
    healthCheckPath: /api/v1/health
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: APP_USERNAME
        sync: false
      - key: APP_PASSWORD
        sync: false
      - key: ANDROID_APP_VERSION
        sync: false
      - key: ANDROID_APP_DOWNLOAD_URL
        sync: false
      - key: ANDROID_APP_NOTES
        sync: false
